// AUTO-GENERATED — extracted by scripts/extract-icc-template.js from a known
// good 33³ ICC DeviceLink reference. The prefix is the ICC header + tag table
// + desc/pseq tags + A2B0 mft2 header + 12-byte identity input tables.
// The suffix is 12-byte identity output tables + 2 padding bytes.
// Between them goes a 33³ × 3 × uint16-BE CLUT (215,622 bytes) generated
// from current curves.
/* eslint-disable */
export const ICC_PREFIX_B64 = "AANLyEFEQkUCEAAAbGlua1JHQiBSR0IgB+oABQALAAAAFQALYWNzcEFQUEwAAAAAbm9uZQAAAAAAAAAAAAAAAAAAAAEAAPbWAAEAAAAA0y1BREJFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADZGVzYwAAAKgAAAB+cHNlcQAAASgAAAAMQTJCMAAAATQAA0qSZGVzYwAAAAAAAAAkQ29sb3JTbWFzaF9EaWZmZXJlbnRVc2VDYXNlc18wMS5wc2QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwc2VxAAAAAAAAAABtZnQyAAAAAAMDIQAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAgACAAD//wAA//8AAP//";
export const ICC_SUFFIX_B64 = "AAD//wAA//8AAP//AAA=";
